// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqrOhUz47etg3ZvC-V5d8Ye7m_NlhkOE4',
    appId: '1:691085027523:web:907bf5829c911ece005a76',
    messagingSenderId: '691085027523',
    projectId: 'orange-project-58131',
    authDomain: 'orange-project-58131.firebaseapp.com',
    storageBucket: 'orange-project-58131.appspot.com',
    measurementId: 'G-W6RQYYPLCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgbUWFmScn5026bJC9oC6hRSi4LwdzPAA',
    appId: '1:691085027523:android:b535b34d85ac2eff005a76',
    messagingSenderId: '691085027523',
    projectId: 'orange-project-58131',
    storageBucket: 'orange-project-58131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATPlWGseKRsVKeN4nVJI0tpLnrNc0BWdU',
    appId: '1:691085027523:ios:8907473ef8de2e08005a76',
    messagingSenderId: '691085027523',
    projectId: 'orange-project-58131',
    storageBucket: 'orange-project-58131.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATPlWGseKRsVKeN4nVJI0tpLnrNc0BWdU',
    appId: '1:691085027523:ios:2a1da1ec66b5a1f8005a76',
    messagingSenderId: '691085027523',
    projectId: 'orange-project-58131',
    storageBucket: 'orange-project-58131.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
